-- Run once in Supabase SQL Editor.
-- Keep your existing users table if it already has these columns.

create table if not exists purchase_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  plan text not null,
  amount numeric not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists withdrawals (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  amount numeric not null,
  address text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- If these columns already exist, these statements will fail harmlessly; add missing columns manually.
alter table users add column if not exists username text default '';
alter table users add column if not exists first_name text default '';
alter table users add column if not exists balance numeric default 0;
alter table users add column if not exists approved boolean default false;
alter table users add column if not exists mining boolean default false;
alter table users add column if not exists plan text default '';
alter table users add column if not exists referrer bigint;
alter table users add column if not exists referrals integer default 0;
alter table users add column if not exists created_at timestamptz default now();

-- For this simple prototype, enable browser access. Tighten RLS before using real money.
alter table users disable row level security;
alter table purchase_requests disable row level security;
alter table withdrawals disable row level security;
